import type { Exercise } from './routine-engine.ts'

/** Mirror de client-pulsefit/src/features/routine-generator/seed-exercises.ts */
export const SEED_EXERCISES: Exercise[] = [
   { id: 'bw-squat', name: 'Sentadilla con peso corporal', pattern: 'squat', muscleGroups: ['cuádriceps','glúteos'], equipmentRequired: ['none','bodyweight'], difficulty: 'beginner', affectedZones: ['rodilla'], description: 'Pies al ancho de hombros.', formTips: [], alternatives: ['goblet-squat'], isCompound: true },
   { id: 'goblet-squat', name: 'Goblet squat con mancuerna', pattern: 'squat', muscleGroups: ['cuádriceps','glúteos','core'], equipmentRequired: ['dumbbells','kettlebell'], difficulty: 'beginner', affectedZones: ['rodilla'], description: '', formTips: [], alternatives: ['bw-squat'], isCompound: true },
   { id: 'back-squat-barbell', name: 'Sentadilla trasera con barra', pattern: 'squat', muscleGroups: ['cuádriceps','glúteos','erectores'], equipmentRequired: ['gym_full'], difficulty: 'forbidden_absolute_beginner', affectedZones: ['rodilla','lumbar'], description: '', formTips: [], alternatives: ['goblet-squat'], isCompound: true },
   { id: 'glute-bridge', name: 'Puente de glúteos', pattern: 'hinge', muscleGroups: ['glúteos','isquios'], equipmentRequired: ['none','bodyweight'], difficulty: 'beginner', affectedZones: ['lumbar'], description: '', formTips: [], alternatives: ['rdl-db'], isCompound: true },
   { id: 'rdl-db', name: 'Peso muerto rumano con mancuernas', pattern: 'hinge', muscleGroups: ['isquios','glúteos','erectores'], equipmentRequired: ['dumbbells'], difficulty: 'beginner', affectedZones: ['lumbar'], description: '', formTips: [], alternatives: ['glute-bridge'], isCompound: true },
   { id: 'deadlift-barbell', name: 'Peso muerto convencional con barra', pattern: 'hinge', muscleGroups: ['isquios','glúteos','erectores','dorsal'], equipmentRequired: ['gym_full'], difficulty: 'forbidden_absolute_beginner', affectedZones: ['lumbar'], description: '', formTips: [], alternatives: ['rdl-db'], isCompound: true },
   { id: 'pushup', name: 'Flexiones de pecho', pattern: 'push_horizontal', muscleGroups: ['pecho','tríceps','hombro anterior'], equipmentRequired: ['none','bodyweight'], difficulty: 'beginner', affectedZones: ['hombro','muñeca'], description: '', formTips: [], alternatives: ['db-floor-press'], isCompound: true },
   { id: 'db-floor-press', name: 'Press de pecho en suelo con mancuernas', pattern: 'push_horizontal', muscleGroups: ['pecho','tríceps'], equipmentRequired: ['dumbbells'], difficulty: 'beginner', affectedZones: ['hombro'], description: '', formTips: [], alternatives: ['pushup'], isCompound: true },
   { id: 'bench-press-barbell', name: 'Press de banca con barra', pattern: 'push_horizontal', muscleGroups: ['pecho','tríceps','hombro anterior'], equipmentRequired: ['gym_full','bench'], difficulty: 'forbidden_absolute_beginner', affectedZones: ['hombro'], description: '', formTips: [], alternatives: ['db-floor-press'], isCompound: true },
   { id: 'db-shoulder-press', name: 'Press de hombros sentado con mancuernas', pattern: 'push_vertical', muscleGroups: ['hombros','tríceps'], equipmentRequired: ['dumbbells'], difficulty: 'beginner', affectedZones: ['hombro'], description: '', formTips: [], alternatives: ['band-shoulder-press'], isCompound: true },
   { id: 'band-shoulder-press', name: 'Press de hombros con banda', pattern: 'push_vertical', muscleGroups: ['hombros','tríceps'], equipmentRequired: ['bands'], difficulty: 'beginner', affectedZones: ['hombro'], description: '', formTips: [], alternatives: ['db-shoulder-press'], isCompound: true },
   { id: 'db-row', name: 'Remo con mancuerna a una mano', pattern: 'pull_horizontal', muscleGroups: ['dorsal','romboides','bíceps'], equipmentRequired: ['dumbbells','bench'], difficulty: 'beginner', affectedZones: ['lumbar'], description: '', formTips: [], alternatives: ['band-row'], isCompound: true },
   { id: 'band-row', name: 'Remo con banda', pattern: 'pull_horizontal', muscleGroups: ['dorsal','romboides','bíceps'], equipmentRequired: ['bands'], difficulty: 'beginner', affectedZones: ['hombro'], description: '', formTips: [], alternatives: ['db-row'], isCompound: true },
   { id: 'assisted-pullup', name: 'Dominadas asistidas con banda', pattern: 'pull_vertical', muscleGroups: ['dorsal','bíceps'], equipmentRequired: ['pullup_bar','bands'], difficulty: 'intermediate', affectedZones: ['hombro','codo'], description: '', formTips: [], alternatives: ['band-pulldown'], isCompound: true },
   { id: 'band-pulldown', name: 'Jalón con banda elástica', pattern: 'pull_vertical', muscleGroups: ['dorsal','bíceps'], equipmentRequired: ['bands'], difficulty: 'beginner', affectedZones: [], description: '', formTips: [], alternatives: ['assisted-pullup'], isCompound: true },
   { id: 'reverse-lunge', name: 'Zancada inversa con peso corporal', pattern: 'lunge', muscleGroups: ['cuádriceps','glúteos'], equipmentRequired: ['none','bodyweight'], difficulty: 'beginner', affectedZones: ['rodilla'], description: '', formTips: [], alternatives: ['db-lunge'], isCompound: true },
   { id: 'db-lunge', name: 'Zancada con mancuernas', pattern: 'lunge', muscleGroups: ['cuádriceps','glúteos'], equipmentRequired: ['dumbbells'], difficulty: 'intermediate', affectedZones: ['rodilla'], description: '', formTips: [], alternatives: ['reverse-lunge'], isCompound: true },
   { id: 'plank', name: 'Plancha', pattern: 'core', muscleGroups: ['abdomen','core','glúteos'], equipmentRequired: ['none','bodyweight'], difficulty: 'beginner', affectedZones: ['hombro','lumbar'], description: '', formTips: [], alternatives: ['dead-bug'], isCompound: false },
   { id: 'dead-bug', name: 'Dead bug', pattern: 'core', muscleGroups: ['core','abdomen'], equipmentRequired: ['none','bodyweight'], difficulty: 'beginner', affectedZones: [], description: '', formTips: [], alternatives: ['plank'], isCompound: false },
   { id: 'bird-dog', name: 'Bird-dog', pattern: 'core', muscleGroups: ['core','erectores','glúteos'], equipmentRequired: ['none','bodyweight'], difficulty: 'beginner', affectedZones: [], description: '', formTips: [], alternatives: ['plank'], isCompound: false },
   { id: 'farmer-walk', name: 'Caminata del granjero', pattern: 'carry', muscleGroups: ['core','antebrazos','trapecios'], equipmentRequired: ['dumbbells','kettlebell'], difficulty: 'beginner', affectedZones: [], description: '', formTips: [], alternatives: [], isCompound: false },

   /* Sprint 11.11 — Ejercicios por modalidad (yoga, HIIT, barre, pilates) */
   { id: 'yoga-mountain', name: 'Postura de la montaña (Tadasana)', pattern: 'core', muscleGroups: ['core','postura'], equipmentRequired: ['none','bodyweight'], difficulty: 'beginner', affectedZones: [], description: 'De pie, pies paralelos, respiración profunda.', formTips: [], alternatives: [], isCompound: false, modalities: ['yoga'] },
   { id: 'yoga-downdog', name: 'Perro boca abajo (Adho Mukha)', pattern: 'push_vertical', muscleGroups: ['hombros','isquios','pantorrillas'], equipmentRequired: ['none','bodyweight'], difficulty: 'beginner', affectedZones: ['hombro'], description: 'Forma de V invertida.', formTips: [], alternatives: ['yoga-childpose'], isCompound: true, modalities: ['yoga'] },
   { id: 'yoga-warrior2', name: 'Guerrero 2 (Virabhadrasana II)', pattern: 'lunge', muscleGroups: ['cuádriceps','glúteos','core'], equipmentRequired: ['none','bodyweight'], difficulty: 'beginner', affectedZones: ['rodilla'], description: 'Pierna delantera flexionada 90°.', formTips: [], alternatives: [], isCompound: true, modalities: ['yoga'] },
   { id: 'yoga-childpose', name: 'Postura del niño (Balasana)', pattern: 'core', muscleGroups: ['espalda baja','caderas'], equipmentRequired: ['none','bodyweight'], difficulty: 'beginner', affectedZones: [], description: 'Rodillas separadas, frente al suelo.', formTips: [], alternatives: [], isCompound: false, modalities: ['yoga'] },
   { id: 'hiit-burpee', name: 'Burpees', pattern: 'push_horizontal', muscleGroups: ['cuerpo completo','cardio'], equipmentRequired: ['none','bodyweight'], difficulty: 'intermediate', affectedZones: ['rodilla','muñeca'], description: 'Sentadilla → plancha → flexión → salto.', formTips: [], alternatives: ['hiit-mountain-climber'], isCompound: true, modalities: ['hiit'] },
   { id: 'hiit-mountain-climber', name: 'Mountain climbers', pattern: 'core', muscleGroups: ['core','hombros','cardio'], equipmentRequired: ['none','bodyweight'], difficulty: 'beginner', affectedZones: [], description: 'Plancha alta, alterna rodillas al pecho.', formTips: [], alternatives: ['hiit-burpee'], isCompound: true, modalities: ['hiit'] },
   { id: 'hiit-jump-squat', name: 'Jump squats', pattern: 'squat', muscleGroups: ['cuádriceps','glúteos','cardio'], equipmentRequired: ['none','bodyweight'], difficulty: 'intermediate', affectedZones: ['rodilla'], description: 'Sentadilla → salto vertical.', formTips: [], alternatives: ['bw-squat'], isCompound: true, modalities: ['hiit'] },
   { id: 'hiit-high-knees', name: 'High knees', pattern: 'core', muscleGroups: ['cardio','core','flexores cadera'], equipmentRequired: ['none','bodyweight'], difficulty: 'beginner', affectedZones: [], description: 'Corre en el lugar elevando rodillas.', formTips: [], alternatives: ['hiit-mountain-climber'], isCompound: true, modalities: ['hiit'] },
   { id: 'barre-plie', name: 'Plié squat', pattern: 'squat', muscleGroups: ['cuádriceps','aductores','glúteos'], equipmentRequired: ['none','bodyweight'], difficulty: 'beginner', affectedZones: ['rodilla'], description: 'Pies muy abiertos, puntas afuera.', formTips: [], alternatives: ['bw-squat'], isCompound: true, modalities: ['barre','pilates'] },
   { id: 'pilates-hundred', name: 'The hundred', pattern: 'core', muscleGroups: ['abdominales','core'], equipmentRequired: ['none','bodyweight'], difficulty: 'beginner', affectedZones: [], description: 'Acostada, piernas a 45°, brazos pulsan.', formTips: [], alternatives: [], isCompound: false, modalities: ['pilates'] },
   { id: 'barre-pulse', name: 'Glute pulses', pattern: 'hinge', muscleGroups: ['glúteos'], equipmentRequired: ['none','bodyweight'], difficulty: 'beginner', affectedZones: [], description: 'Cuadrupedia, eleva pierna, pulsaciones cortas.', formTips: [], alternatives: [], isCompound: false, modalities: ['barre','pilates'] },
   { id: 'pilates-roll-up', name: 'Roll up', pattern: 'core', muscleGroups: ['abdominales','core','flexibilidad'], equipmentRequired: ['none','bodyweight'], difficulty: 'beginner', affectedZones: ['lumbar'], description: 'Sube despacio vértebra por vértebra.', formTips: [], alternatives: ['pilates-hundred'], isCompound: false, modalities: ['pilates'] }
]
