/* Barrel de componentes reusables. */
export { TitleUI } from './TitleUI'
export { LoaderUI } from './LoaderUI'
export { EmptyState } from './EmptyState'
export { ErrorBoundary } from './ErrorBoundary'
export { MealsPerDayDialog } from './MealsPerDayDialog'
export { ShoppingListDialog } from './ShoppingListDialog'
export { InfoTooltip } from './InfoTooltip'
export type { InfoTopicKey } from './InfoTooltip'
export { SwapIngredientDialog } from './SwapIngredientDialog'
export { LogSetDialog } from './LogSetDialog'
export { MealLogDialog } from './MealLogDialog'
export { WeightLogDialog } from './WeightLogDialog'
export { QuickActionFAB } from './QuickActionFAB'
export { FavoritesEditor } from './FavoritesEditor'
export { ResetAccountDialog } from './ResetAccountDialog'
export * from './ui'
